server:
  port: 8769

spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
    #preferIpAddress: true
  client:
    #registerWithEureka: false
    #fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/